### ISSUE TITLE
Parser error: pointer being freed was not allocated

### ISSUE THREAD

**Issue by Thegaram** [cucumber/cucumber.ml#2]
Hey, great project, thanks for making Cucumber available to the OCaml community!

I was playing around with the provided example `test.ml` file and noticed something strange.

```gherkin
Feature: Cucumber.ml test

  Scenario: simple docstring
    Given a simple DocString
    When I run my test
    Then I should receive the test results

  Scenario: another test
    Given DocString with alternative separator inside
    When I run my other test
    Then I should receive the different test results
```

Running the tests on the file above, I get a segmentation fault:

```
$ ./cucumber_run test.cmxs test.feature 
Segmentation fault: 11
$ ./cucumber_run test.cmxs test.feature 
cucumber_run(22904,0x7fffa56b0340) malloc: *** error for object 0x7f8f9fd02870: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

However, if I put anything after the second pickle, the test just runs fine:

```gherkin
Feature: Cucumber.ml test

  Scenario: simple docstring
    Given a simple DocString
    When I run my test
    Then I should receive the test results

  Scenario: another test
    Given DocString with alternative separator inside
    When I run my other test
    Then I should receive the different test results
#
```

(Notice the `#` in the last line.)

```
$ ./cucumber_run test.cmxs test.feature 
Could not find step: I should receive the test results
Could not find step: I run my test
Could not find step: I should receive the different test results
Could not find step: I run my other test
Ambigious match: DocString with alternative separator inside
UUUFUU
```

I've only encountered this error with two pickles, works fine with 1 / 3 or more. I suspect this is some error in the parser implementation?

**Comment by Thegaram** [comment]
Upon further testing, this seems to be two separate errors.

1. Segmentation fault

This one seems to be associated with `locs->location_count` having an invalid (seemingly random) value in `create_ocaml_loc_list`. Seems to be an issue in `gherkin-c` for me. @aslakhellesoy?

2. pointer being freed was not allocated

This one comes from `Event_delete((const Event*)pickle_event)` inside `load_feature_file`.

**Comment by aslakhellesoy** [comment]
Hi @Thegaram if you've found an error in gherkin-c, could you please create an issue or pull request here?

https://github.com/cucumber/gherkin-c

Do you have any suggestions @cyocum?

Thanks!

**Comment by cyocum** [comment]
Thanks @Thegaram!  I am glad that you like it.   I haven't really announced it to the OCaml community at large yet as I have a bunch of stuff that I would love to do to make it better.  If you have any suggestions, please let me know.  Anyway, I am looking into the problems that you have encountered and I hope to have some more information soon.

**Comment by cyocum** [comment]
I am not able to reproduce this at the moment.  I will keep at it and attempt to reproduce this.  It does seem very odd.

**Comment by Thegaram** [comment]
Interesting. I installed gherkin-c like this:

```
gherkin-c $ mkdir build
gherkin-c $ cd build
gherkin-c $ cmake ..
gherkin-c $ cmake --build . --target install
```

And then installed cucumber.ml like this:

```
cucumber.ml $ make build_library
cucumber.ml $ make install_library
cucumber.ml $ make build_runtime
cucumber.ml $ make build_test
cucumber.ml $ ./cucumber_run test.cmxs test.feature 
cucumber_run(31361,0x7fffa56b0340) malloc: *** error for object 0x7ff0f2405370: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

I did make one change: removed the `--no-as-needed` flag from the `build_runtime` script because it doesn't seem to be supported on macOS. But this does not seem to be relevant.

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.3 (17D102)
      Kernel Version: Darwin 17.4.0
      ...

$ ocaml --version
The OCaml toplevel, version 4.06.1

$ opam --version
2.0.0~rc

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
```

**Comment by cyocum** [comment]
I have a hunch I know what the problem might be.  Can you do an `ldd` on cucumber_run? I only wrote the shared library code for `make` and not `cmake` so the `.so` file may not exist and that could cause the problems that you are seeing.  It may be related to a [gherkin-c](https://github.com/cucumber/gherkin-c/issues/7) issue about inconstant build instructions.

**Comment by Thegaram** [comment]
```
$ otool -L ./cucumber_run
./cucumber_run:
	@rpath/libgherkin.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

I tried `make cli` from gherkin-c's CONTRIBUTING, but it didn't help:

```
$ make cli
cd src; /Applications/Xcode.app/Contents/Developer/usr/bin/make CC=cc cli
make[1]: Nothing to be done for `cli'.
```

I am not sure though that this is the problem, as the lib works for different inputs, and it sometimes works even for the faulty input, e.g. here are the outputs from three consecutive runs:

```
$ ./cucumber_run test.cmxs test.feature 
cucumber_run(33151,0x7fffa56b0340) malloc: *** error for object 0x7ff1c4d01e00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

$ ./cucumber_run test.cmxs test.feature 
Segmentation fault: 11

$ ./cucumber_run test.cmxs test.feature 
Could not find step: I should receive the test results
Could not find step: I run my test
Could not find step: 
Could not find step: I run my other test
Ambigious match: DocString with alternative separator inside
UUUFUU
```

**Comment by cyocum** [comment]
Thank you for the extra information.  :( This is very odd.  I do not have a hypothesis yet.
