### ISSUE TITLE
gherkin-c dependency building fails

### ISSUE THREAD

**Issue by subpardaemon** [cucumber/cucumber.ml#26]
This is more a note than an issue for people like me who have to put together working cucumber tests in OCaml: the gherkin-c library does not compile in its current form on *nix machines.

I've created a patch and submitted an issue in both the subrepo and the monorepo. For a solution, see this:

https://github.com/cucumber/cucumber/issues/470

**Comment by cyocum** [comment]
Thanks! Apologies for not seeing this issue sooner.  I used the Makefile which should work and not the CMake file as I do not know anything about CMake really.  I know this is suboptimal.  There used to be a issue open for this but I cannot find it at the moment. So you should be able to just do `make` and you will get a libgherkin.so file out.  Let me know if that does not work for you and I will look into it.
