### ISSUE TITLE
Build dies 

### ISSUE THREAD

**Issue by subpardaemon** [cucumber/cucumber.ml#28]
build fails with the following messages:
``
ocamlc lib/.cucumber.objs/byte/cucumber__Step.{cmi,cmti} (exit 2)
(cd _build/default && /home/opam/.opam/4.07/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w +42 -g -bin-annot -I lib/.cucumber.objs/byte -I /home/opam/.opam/4.07/lib/base -I /home/opam/.opam/4.07/lib/base/caml -I /home/opam/.opam/4.07/lib/base/shadow_stdlib -I /home/opam/.opam/4.07/lib/cmdliner -I /home/opam/.opam/4.07/lib/re -I /home/opam/.opam/4.07/lib/re/perl -I /home/opam/.opam/4.07/lib/seq -I /home/opam/.opam/4.07/lib/sexplib0 -no-alias-deps -opaque -open Cucumber__ -o lib/.cucumber.objs/byte/cucumber__Step.cmi -c -intf lib/step.mli)
File "lib/step.mli", line 14, characters 32-41:
Error (warning 3): deprecated: Re.groups
Use Group.t
  ocamlmklib lib/dllcucumber_stubs.so,lib/libcucumber_stubs.a (exit 2)
(cd _build/default && /home/opam/.opam/4.07/bin/ocamlmklib.opt -g -o lib/cucumber_stubs lib/gherkin_intf.o -lgherkin)
/usr/bin/ld: //usr/local/lib/libgherkin.a(unicode_utilities.c.o): relocation R_X86_64_PC32 against symbol `UnicodeUtilities_is_utf16_surrogate' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
``
OPAM 2.0.0~rc2
OCAML 4.07.0+beta2
gherkin-c is installed

please advise

**Comment by subpardaemon** [comment]
issue #1 (-fPIC complaints) is caused by https://github.com/cucumber/gherkin-c/commit/0d7054643ff9f1ce2f1e520eebe3b61dfd4510e1 . re-adding the SHARED token to the cmake file fixes that issue. the remaining "File "lib/step.mli", line 14, characters 32-41: Error (warning 3): deprecated: Re.groups Use Group.t" issue is still outstanding.

**Comment by subpardaemon** [comment]
issue #2 seems to be resolved in the update_re branch. why is it not merged back in main? is there an ETA for this merge?

**Comment by cyocum** [comment]
The update_re branch has been merged into master and fixes the regular expression problem.
