### ISSUE TITLE
Build fails : incompatibility between gherkin-c and gherkin.ml ?

### ISSUE THREAD

**Issue by RuyBlast** [cucumber/cucumber.ml#29]
Hi !
I built gherkin-c (but as I did not succeeded in exposing libgherkin.so on my system, I just took all .c and .h needed files, puted them into a libgh directory and added -I<path_to_cucumber.ml>/cucumber.ml/libgh option to c_flags in lib/dune). When I run `dune build`, I get following long error message that states that there are incompatible declarations between c code provided by gherkin-c and expected c code, if I understand :

    ocamlopt lib/.cucumber.objs/cucumber__Table.{cmx,o} (exit 2)
(cd _build/default && /home/milan/.opam/todolist/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w +42 -g -I lib/.cucumber.objs -I lib/.cucumber.objs/.private -I /home/milan/.opam/todolist/lib/base -I /home/milan/.opam/todolist/lib/base/caml -I /home/milan/.opam/todolist/lib/base/shadow_stdlib -I /home/milan/.opam/todolist/lib/bytes -I /home/milan/.opam/todolist/lib/cmdliner -I /home/milan/.opam/todolist/lib/re -I /home/milan/.opam/todolist/lib/re/perl -I /home/milan/.opam/todolist/lib/result -I /home/milan/.opam/todolist/lib/seq -I /home/milan/.opam/todolist/lib/sexplib0 -intf-suffix .ml -no-alias-deps -opaque -open Cucumber__ -o lib/.cucumber.objs/cucumber__Table.cmx -c -impl lib/table.ml)
File "lib/table.ml", line 33, characters 4-35:
Error: The constructor Base.List.Or_unequal_lengths.Ok
       belongs to the variant type
         Base.List.Or_unequal_lengths.t = Base__List.Or_unequal_lengths.t
       but a constructor was expected belonging to the variant type option
      ocamlc lib/.cucumber.objs/cucumber__Table.{cmo,cmt} (exit 2)
(cd _build/default && /home/milan/.opam/todolist/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w +42 -g -bin-annot -I lib/.cucumber.objs -I lib/.cucumber.objs/.private -I /home/milan/.opam/todolist/lib/base -I /home/milan/.opam/todolist/lib/base/caml -I /home/milan/.opam/todolist/lib/base/shadow_stdlib -I /home/milan/.opam/todolist/lib/bytes -I /home/milan/.opam/todolist/lib/cmdliner -I /home/milan/.opam/todolist/lib/re -I /home/milan/.opam/todolist/lib/re/perl -I /home/milan/.opam/todolist/lib/result -I /home/milan/.opam/todolist/lib/seq -I /home/milan/.opam/todolist/lib/sexplib0 -intf-suffix .ml -no-alias-deps -opaque -open Cucumber__ -o lib/.cucumber.objs/cucumber__Table.cmo -c -impl lib/table.ml)
File "lib/table.ml", line 33, characters 4-35:
Error: The constructor Base.List.Or_unequal_lengths.Ok
       belongs to the variant type
         Base.List.Or_unequal_lengths.t = Base__List.Or_unequal_lengths.t
       but a constructor was expected belonging to the variant type option
      ocamlc lib/gherkin_intf.o (exit 2)
(cd _build/default/lib && /home/milan/.opam/todolist/bin/ocamlc.opt -g -I /home/milan/.opam/todolist/lib/base -I /home/milan/.opam/todolist/lib/base/caml -I /home/milan/.opam/todolist/lib/base/shadow_stdlib -I /home/milan/.opam/todolist/lib/bytes -I /home/milan/.opam/todolist/lib/cmdliner -I /home/milan/.opam/todolist/lib/re -I /home/milan/.opam/todolist/lib/re/perl -I /home/milan/.opam/todolist/lib/result -I /home/milan/.opam/todolist/lib/seq -I /home/milan/.opam/todolist/lib/sexplib0 -ccopt -I/usr/include/gherkin -ccopt -I/home/milan/Programs/cucumber.ml/libgh -o gherkin_intf.o gherkin_intf.c)
gherkin_intf.c: In function ‘load_feature_file’:
gherkin_intf.c:67:94: error: too few arguments to function ‘AstBuilder_get_result’
     const GherkinDocumentEvent* gherkin_document_event = GherkinDocumentEvent_new(sFileName, AstBuilder_get_result(builder));
                                                                                              ^~~~~~~~~~~~~~~~~~~~~
In file included from gherkin_intf.c:13:0:
/home/milan/Programs/cucumber.ml/libgh/ast_builder.h:15:24: note: declared here
 const GherkinDocument* AstBuilder_get_result(Builder* builder, const char* uri);
                        ^~~~~~~~~~~~~~~~~~~~~
gherkin_intf.c:67:83: warning: passing argument 1 of ‘GherkinDocumentEvent_new’ from incompatible pointer type [-Wincompatible-pointer-types]
     const GherkinDocumentEvent* gherkin_document_event = GherkinDocumentEvent_new(sFileName, AstBuilder_get_result(builder));
                                                                                   ^~~~~~~~~
In file included from gherkin_intf.c:14:0:
/home/milan/Programs/cucumber.ml/libgh/gherkin_document_event.h:16:29: note: expected ‘const GherkinDocument * {aka const struct GherkinDocument *}’ but argument is of type ‘char *’
 const GherkinDocumentEvent* GherkinDocumentEvent_new(const GherkinDocument* gherkin_document);
                             ^~~~~~~~~~~~~~~~~~~~~~~~
gherkin_intf.c:67:58: error: too many arguments to function ‘GherkinDocumentEvent_new’
     const GherkinDocumentEvent* gherkin_document_event = GherkinDocumentEvent_new(sFileName, AstBuilder_get_result(builder));
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from gherkin_intf.c:14:0:
/home/milan/Programs/cucumber.ml/libgh/gherkin_document_event.h:16:29: note: declared here
 const GherkinDocumentEvent* GherkinDocumentEvent_new(const GherkinDocument* gherkin_document);
                             ^~~~~~~~~~~~~~~~~~~~~~~~
gherkin_intf.c:69:19: error: too few arguments to function ‘Compiler_compile’
     result_code = Compiler_compile(compiler, gherkin_document_event->gherkin_document);
                   ^~~~~~~~~~~~~~~~
In file included from gherkin_intf.c:15:0:
/home/milan/Programs/cucumber.ml/libgh/compiler.h:19:5: note: declared here
 int Compiler_compile(Compiler* compiler, const GherkinDocument* gherkin_document, const wchar_t* source);
     ^~~~~~~~~~~~~~~~
gherkin_intf.c:75:52: warning: passing argument 1 of ‘PickleEvent_new’ from incompatible pointer type [-Wincompatible-pointer-types]
  const PickleEvent* pickle_event = PickleEvent_new(sFileName, Compiler_next_pickle(compiler));
                                                    ^~~~~~~~~
In file included from gherkin_intf.c:20:0:
/home/milan/Programs/cucumber.ml/libgh/pickle_event.h:19:20: note: expected ‘const Pickle * {aka const struct Pickle *}’ but argument is of type ‘char *’
 const PickleEvent* PickleEvent_new(const Pickle* pickle);
                    ^~~~~~~~~~~~~~~
gherkin_intf.c:75:36: error: too many arguments to function ‘PickleEvent_new’
  const PickleEvent* pickle_event = PickleEvent_new(sFileName, Compiler_next_pickle(compiler));
                                    ^~~~~~~~~~~~~~~
In file included from gherkin_intf.c:20:0:
/home/milan/Programs/cucumber.ml/libgh/pickle_event.h:19:20: note: declared here
 const PickleEvent* PickleEvent_new(const Pickle* pickle);
                    ^~~~~~~~~~~~~~~

What do you think about it ? Could I work around this ? (maybe coming back to an previous commit of gherkin-c ?)
Thank you for your help :) (I would really appreciate to use this cool stuff ;) )

[EDIT] There is no incompatibility between gherkin-c and gherkin.ml, I just did not have the proper dependencies. So if you have the same problem I had, compare packages in cucumber.opam files and packages installed on your current switch, or just create a new switch with proper dependencies.

**Comment by cyocum** [comment]
I believe that this is caused by the updating of gherkin-c to Gherkin 7.  A workaround would be to clone the cucumber monorepo then checking out the tag gherkin-5.2.0 (it should be this commit in the cucumber repo https://github.com/cucumber/cucumber/commit/47788c4f5e2296346e60a68549f130c522691065).  This should work with the current version of cucumber.ml.  Let me know if this workaround works for you.  Someone will need to spend some time updating the gherkin-c version to Gherkin 7.

**Comment by RuyBlast** [comment]
Hi ! Thanks a lot cyocum for your answer ! I did not find the tag for gherkin-5.2.0 in gherkin-c, so I came back to version 5.1.0 instead. Then I built (`make default`) gherkin-c, exposed the library to cucumber.ml, and built (`dune build`) cucumber.ml which failed with :
```
      ocamlc lib/.cucumber.objs/cucumber__Table.{cmo,cmt} (exit 2)
(cd _build/default && /home/milan/.opam/ocsigen_start/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w +42 -g -bin-annot -I lib/.cucumber.objs -I lib/.cucumber.objs/.private -I /home/milan/.opam/ocsigen_start/lib/base -I /home/milan/.opam/ocsigen_start/lib/base/caml -I /home/milan/.opam/ocsigen_start/lib/base/shadow_stdlib -I /home/milan/.opam/ocsigen_start/lib/bytes -I /home/milan/.opam/ocsigen_start/lib/cmdliner -I /home/milan/.opam/ocsigen_start/lib/re -I /home/milan/.opam/ocsigen_start/lib/re/perl -I /home/milan/.opam/ocsigen_start/lib/result -I /home/milan/.opam/ocsigen_start/lib/seq -I /home/milan/.opam/ocsigen_start/lib/sexplib0 -intf-suffix .ml -no-alias-deps -opaque -open Cucumber__ -o lib/.cucumber.objs/cucumber__Table.cmo -c -impl lib/table.ml)
File "lib/table.ml", line 33, characters 4-35:
Error: The constructor Base.List.Or_unequal_lengths.Ok
       belongs to the variant type
         Base.List.Or_unequal_lengths.t = Base.List.Or_unequal_lengths.t
       but a constructor was expected belonging to the variant type option
    ocamlopt lib/.cucumber.objs/cucumber__Table.{cmx,o} (exit 2)
(cd _build/default && /home/milan/.opam/ocsigen_start/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w +42 -g -I lib/.cucumber.objs -I lib/.cucumber.objs/.private -I /home/milan/.opam/ocsigen_start/lib/base -I /home/milan/.opam/ocsigen_start/lib/base/caml -I /home/milan/.opam/ocsigen_start/lib/base/shadow_stdlib -I /home/milan/.opam/ocsigen_start/lib/bytes -I /home/milan/.opam/ocsigen_start/lib/cmdliner -I /home/milan/.opam/ocsigen_start/lib/re -I /home/milan/.opam/ocsigen_start/lib/re/perl -I /home/milan/.opam/ocsigen_start/lib/result -I /home/milan/.opam/ocsigen_start/lib/seq -I /home/milan/.opam/ocsigen_start/lib/sexplib0 -intf-suffix .ml -no-alias-deps -opaque -open Cucumber__ -o lib/.cucumber.objs/cucumber__Table.cmx -c -impl lib/table.ml)
File "lib/table.ml", line 33, characters 4-35:
Error: The constructor Base.List.Or_unequal_lengths.Ok
       belongs to the variant type
         Base.List.Or_unequal_lengths.t = Base.List.Or_unequal_lengths.t
       but a constructor was expected belonging to the variant type option
```
I am soon going to `git checkout 47788c4` directly from cucumber repository (as this commit does not belong to gherkin-c repository) as you suggests precisely and I report you back my result.
Best !

**Comment by cyocum** [comment]
Hi! I think I know what the problem with that build message is.  Base changed the way in which it deals with the List.zip function (see https://github.com/janestreet/base/commit/4e8479dfe66f6baf51157726eb3eb56107bb8dfa#diff-5edf81e72b2c10e016281d13144a6f0e). The library uses Base 0.12.0 and above so it looks like you have an older version of Base.  Look in the [cucumber.opam](https://github.com/cucumber/cucumber.ml/blob/master/cucumber.opam) to see what version Cucumber.ml supports.

**Comment by RuyBlast** [comment]
> Hi! I think I know what the problem with that build message is. Base changed the way in which it deals with the List.zip function (see [janestreet/base@4e8479d#diff-5edf81e72b2c10e016281d13144a6f0e](https://github.com/janestreet/base/commit/4e8479dfe66f6baf51157726eb3eb56107bb8dfa#diff-5edf81e72b2c10e016281d13144a6f0e)). The library uses Base 0.12.0 and above so it looks like you have an older version of Base. Look in the [cucumber.opam](https://github.com/cucumber/cucumber.ml/blob/master/cucumber.opam) to see what version Cucumber.ml supports.

Hi cyocum ! You where totally right, I had a dependency problem. Installing the proper packages I could build Cucumber.ml.
I got the proper output:
```
$ dune build && dune install
Installing /home/milan/.opam/cucumber/lib/cucumber/META
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber.a
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber.cma
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber.cmxa
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber.cmxs
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Docstring.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Docstring.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Docstring.cmti
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Docstring.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Lib.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Lib.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Lib.cmti
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Lib.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Location.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Location.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Location.cmti
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Location.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Outcome.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Outcome.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Outcome.cmti
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Outcome.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Pickle.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Pickle.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Pickle.cmti
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Pickle.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Report.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Report.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Report.cmti
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Report.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Step.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Step.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Step.cmti
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Step.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Table.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Table.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Table.cmti
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Table.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Tag.cmi
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Tag.cmt
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Tag.cmti
Installing /home/milan/.opam/cucumber/lib/cucumber/cucumber__Tag.cmx
Installing /home/milan/.opam/cucumber/lib/cucumber/docstring.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/docstring.mli
Installing /home/milan/.opam/cucumber/lib/cucumber/dune-package
Installing /home/milan/.opam/cucumber/lib/cucumber/lib.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/lib.mli
Installing /home/milan/.opam/cucumber/lib/cucumber/libcucumber_stubs.a
Installing /home/milan/.opam/cucumber/lib/cucumber/location.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/location.mli
Installing /home/milan/.opam/cucumber/lib/cucumber/opam
Installing /home/milan/.opam/cucumber/lib/cucumber/outcome.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/outcome.mli
Installing /home/milan/.opam/cucumber/lib/cucumber/pickle.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/pickle.mli
Installing /home/milan/.opam/cucumber/lib/cucumber/report.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/report.mli
Installing /home/milan/.opam/cucumber/lib/cucumber/step.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/step.mli
Installing /home/milan/.opam/cucumber/lib/cucumber/table.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/table.mli
Installing /home/milan/.opam/cucumber/lib/cucumber/tag.ml
Installing /home/milan/.opam/cucumber/lib/cucumber/tag.mli
Installing /home/milan/.opam/cucumber/doc/cucumber/LICENSE
Installing /home/milan/.opam/cucumber/doc/cucumber/README.md
Installing /home/milan/.opam/cucumber/lib/stublibs/dllcucumber_stubs.so

```
However, cucumber is not list in opam list and it is like I have to manually link all files of the library to compile test.ml. I think I am doing something wrong but I cannot figure out what.
Thanks a lot for your help !

**Comment by cyocum** [comment]
Hi,

It is listed in `ocamlfind list | egrep cucumber` so you should be able to use it in a `ocamlfind opt`.  See the Makefile in the repo for an example of how to use it.  Opam and ocamfind are different systems and `dune install` will install it for ocamlfind but not show it in Opam.  I have not had the time to do a real cucumber release via Opam as it is an involved process.

No problem.

**Comment by RuyBlast** [comment]
Indeed it is properly listed in `ocamlfind list | egrep cucumber` , I 'll study the doc of ocamlfind to run it so.
Thanks again :)
