### ISSUE TITLE
Submodule for gherkin-c relies on mirror repos which are going away

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber.ml#39]
### 🤔 What's the problem you've observed?

This repo relies on the https://github.com/cucumber/gherkin-c mirror repo, generated from the main https://github.com/cucumber/common repo. We have a strategy (https://github.com/cucumber/common/issues/1550) to retire these mirror repos and the infrastructure that maintains them.

### ✨ Do you have a proposal for making it better?

Once the Gherkin project has been moved out of the monorepo, we'll need to either update it to continue publishing a mirror repo of gherkin-c, or ideally we'd change this project to be able to handle a submodule that contains the whole gherkin project. It seems that would be simpler.

### 📚 Any additional context?

https://github.com/orgs/cucumber/projects/12

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by tmcgilchrist** [comment]
#41 switches to the main https://github.com/cucumber/common repo.

**Comment by mattwynne** [comment]
@tmcgilchrist thanks, but I think there's been a misunderstanding. The code for gherkin has moved into the https://github.com/cucumber/gherkin repo

**Comment by tmcgilchrist** [comment]
Yes of course, that is the repo I’m using in the PR.

**Comment by mpkorstanje** [comment]
Resolved by #41.

@mattwynne the PR had the correct url, the url in the message was a typo.
