### ISSUE TITLE
Async step definitions

### ISSUE THREAD

**Issue by Thegaram** [cucumber/cucumber.ml#9]
Right now this library only supports synchronous step definitions that are executed sequentially. However, it would be nice to be able to use asynchronous step definitions as well.

My use case is sending an HTTP request in a step definition and only proceeding once the response has been received. So basically only execute subsequent steps (from the same pickle), when the associated Lwt promise has been resolved. (Note: I am using Cohttp.)

This way, as long as steps do not have side effects, pickles could be executed parallelly.

I know in cucumber-js this functionality has been implemented using callbacks:

```js
When('I run my test', function(callback) {
  do_something_asynchronously.then(callback);
});
```

@cyocum what do you think, what would be the best/idiomatic way to achieve this in OCaml?

**Comment by cyocum** [comment]
I have started a process of discovery by using Lwt.  You can have a look at what I am doing on the [async](https://github.com/cucumber/cucumber.ml/tree/async) branch.  I am not sure where it will go just yet but I am hoping to address the async issue you identified.  Please feel free to comment on the code.

**Comment by cyocum** [comment]
I have just pushed some more code.  This makes some fundamental changes to the way in which this works.  Basically, you cannot have both non-async and async together like you can with Javascript (as far as I understand it anyway).  So, at the moment there is no non-async methods on this branch.  I will need to think about how to accommodate this and #6.

Anyway, try it out and let me know what you think.

**Comment by Thegaram** [comment]
I decided to synchronously wait for the Cohttp request, so this is not a blocking issue for me.

```ocaml
_When empty (Re_perl.compile_pat "I make a request") (fun gs _ ->
  let (resp, body) = Lwt_main.run (Cohttp.Client.get url) in
  ...; (* store the response somewhere *)
  Pass
)
```

**Comment by Thegaram** [comment]
@cyocum I think it might make more sense to figure out #6 first and then solve the async issue in a way that steps that depend on each other are run sequentially. Please see my comments on 07dbab2dfff0f73b43ad026c2221c6452187ef3b for more details.

**Comment by Thegaram** [comment]
Having used the library for a while, I am not sure anymore that this feature is needed. In most use cases, it's perfectly fine to just wait for the async task to finish before proceeding to the next step (see above). Having async step definitions would probably mean forcing all stepdefs to be async, which would make the library slightly harder to use.

I'll close this issue now, let's reopen it if we find a more relevant use case.
